// Copyright (c) rubicon IT GmbH, www.rubicon.eu
//
// See the NOTICE file distributed with this work for additional information
// regarding copyright ownership.  rubicon licenses this file to you under 
// the Apache License, Version 2.0 (the "License"); you may not use this 
// file except in compliance with the License.  You may obtain a copy of the 
// License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the 
// License for the specific language governing permissions and limitations
// under the License.
// 

using System;
using System.Collections.Generic;
using System.Reflection;
using Remotion.TypePipe.MutableReflection;

namespace Remotion.TypePipe.CodeGeneration
{
  /// <summary>
  /// Instances of this interface manage the code generated by the pipeline.
  /// </summary>
  /// <remarks>
  /// Implementations of this interface must not use other pipeline APIs themselves as this could cause deadlocks in a multi-threaded environment.
  /// </remarks>
  public interface IGeneratedCodeFlusher
  {
    /// <summary>
    /// Gets the directory in which assemblies will be saved when <see cref="FlushCodeToDisk"/> is invoked; <see langword="null"/> means the
    /// current working directory.
    /// </summary>
    /// <value>The assembly directory path or <see langword="null"/>.</value>
    string AssemblyDirectory { get; }

    /// <summary>
    /// Gets the current assembly name pattern, that is, a pattern used to determine the assembly name the next time <see cref="FlushCodeToDisk"/> is
    /// invoked. To ensure unique assembly file names use the placeholder <c>{counter}</c>, which will be replaced with a unique number.
    /// If the name pattern does not contain the placeholder, calls to <see cref="FlushCodeToDisk"/> will overwrite previously saved assemblies.
    /// </summary>
    /// <value>The assembly name pattern; the default is <c>TypePipe_GeneratedAssembly_{counter}</c>.</value>
    string AssemblyNamePattern { get; }

    /// <summary>
    /// Sets the directory in that assemblies will be saved, when <see cref="FlushCodeToDisk"/> is called.
    /// If <see langword="null"/> is specified, the assemblies are saved to the current working directory.
    /// </summary>
    /// <param name="assemblyDirectory">The assembly directory, or <see langword="null"/>.</param>
    /// <exception cref="InvalidOperationException">
    /// If the pipeline already generated a type (because it was requested) into the new assembly, the assembly directory cannot be changed.
    /// </exception>
    void SetAssemblyDirectory (string assemblyDirectory);

    /// <summary>
    /// Sets the assembly name pattern, that is, a pattern used to determine the assembly name the next time <see cref="FlushCodeToDisk"/> is
    /// invoked. To ensure unique assembly file names use the placeholder <c>{counter}</c>, which will be replaced with a unique number.
    /// If the name pattern does not contain the placeholder, calls to <see cref="FlushCodeToDisk"/> will overwrite previously saved assemblies.
    /// </summary>
    /// <remarks>Note that the assembly name pattern should not include a file extension (<c>.dll</c>).</remarks>
    /// <param name="assemblyNamePattern">
    /// The assembly name pattern (might include <c>{counter}</c> placeholder; should not include the <c>.dll</c> file extension).
    /// </param>
    /// <exception cref="InvalidOperationException">
    /// If the pipeline already generated a type (because it was requested) into the new assembly, the assembly name pattern cannot be changed.
    /// </exception>
    void SetAssemblyNamePattern (string assemblyNamePattern);

    /// <summary>
    /// Saves all types that have been generated since the last call to this method into a new <see cref="Assembly"/> on disk.
    /// The file name of the assembly is derived from <see cref="AssemblyNamePattern"/> plus the file ending <c>.dll</c>.
    /// The assembly is written to the directory defined by <see cref="AssemblyDirectory"/>.
    /// If <see cref="AssemblyDirectory"/> is <see langword="null"/> the assembly is saved in the current working directory.
    /// </summary>
    /// <param name="assemblyAttributes">A number of custom <see cref="Attribute"/>s that should be attached to the saved assembly.</param>
    /// <remarks>
    /// If no new types have been generated since the last call to <see cref="FlushCodeToDisk"/>, this method does nothing
    /// and returns <see langword="null"/>.
    /// </remarks>
    /// <returns>The absolute path to the saved assembly file, or <see langword="null"/> if no assembly was saved.</returns>
    string FlushCodeToDisk (IEnumerable<CustomAttributeDeclaration> assemblyAttributes);
  }
}