// Copyright (c) rubicon IT GmbH, www.rubicon.eu
//
// See the NOTICE file distributed with this work for additional information
// regarding copyright ownership.  rubicon licenses this file to you under 
// the Apache License, Version 2.0 (the "License"); you may not use this 
// file except in compliance with the License.  You may obtain a copy of the 
// License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the 
// License for the specific language governing permissions and limitations
// under the License.
// 

using System;

namespace Remotion.TypePipe
{
  /// <summary>
  /// A key used to identify types generated by the pipeline.
  /// It should include the <see cref="IParticipant"/> configuation and other data that might influence the modifications specified by a participant.
  /// However, implementations should not encode the requested type itself, as this is already handled by the pipeline.
  /// </summary>
  /// <remarks>
  /// Implementation notes:
  /// <see cref="Equals"/> and <see cref="GetHashCode"/> must return the same result for invocations with the same input.
  /// This can be easily achieved by making the implementation immutable.
  /// </remarks>
  public abstract class CacheKey
  {
    public abstract override bool Equals (object other);

    public abstract override int GetHashCode ();
  }
}